### ISSUE TITLE
Use of 'async' variable name breaks erequests on 3.7 and later

### ISSUE THREAD

**Issue by AGSPhoenix** [saghul/erequests#6]
```
Traceback (most recent call last):
  File "eve.py", line 18, in <module>
    import erequests
  File "/mnt/d/Users/Peter/Desktop/scrape_site/testing/git/eve/venv/lib/python3.7/site-packages/erequests.py", line 101
    async = AsyncRequestFactory
          ^
SyntaxError: invalid syntax
```

> ## What’s New In Python 3.7
> **Backwards incompatible syntax changes:**
> async and await are now reserved keywords.

https://docs.python.org/3/whatsnew/3.7.html

Should be a simple find/replace to fix.

**Comment by saghul** [comment]
It's slightly more annoying than that, alas: the API currently exposes the methods in that async namespace. `erequests.async.get()` for example. I think it would be a good idea to get rid of the `async` there altogether and say that the methods exposed by this library are async, period.

If you feel like sending a patch, PRs are welcome :-)

**Comment by AGSPhoenix** [comment]
Oh derp, I hadn't actually looked at the async functions. Don't submit issues at 1 AM, kids.

I'm not sure exactly what you'd want from a PR. I don't see any way to avoid breaking the API for the async functions, but leaving the non-async ones intact would hopefully minimize the damage. Would removing the `async` references and just replacing them with a bunch of `get_async` etc. methods work for you?

**Comment by saghul** [comment]
Yeah, that would work!
